server:
  port: ${PORT:8080} # The port the application will run on; uses the PORT environment variable or defaults to 0 if not set.

spring:
  application:
    name: api-credit # Name of the Spring application.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC driver class.
    url: jdbc:mysql://192.168.15.14:3306/credit_hml_contasDB?createDatabaseIfNotExist=true # Database connection URL with auto-create option.
    username: rcosta # Database username.
    password: rafa1234 # Database password.
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the database schema to match the entities.
    show-sql: true # Logs SQL queries executed by Hibernate.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Hibernate dialect for MySQL 8.
  jmx:
    enabled: true # Enable Java Management Extensions (JMX) for monitoring.
    mbean-domain: metrics # Set the JMX domain to "metrics".

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

jar:
  name: api-credit # Name of the application's JAR file.
