version: "3.8"

services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=hml
    networks:
      - hml_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway:
    build:
      context: ./gateway
    container_name: gateway
    ports:
      - "8765:8765"
    depends_on:
      - server
    environment:
      - SPRING_PROFILES_ACTIVE=hml
    networks:
      - hml_network
    entrypoint: ["sh", "-c", "./wait-for-it.sh server_hml:8761 -- ./start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-account-1:
    build:
      context: ./microservices/api-account
    container_name: api_account_1_hml
    ports:
      - "8081:8080"
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=hml
      - SPRING_APPLICATION_INSTANCE_ID=account-1
      - EUREKA_SERVER_URL=http://server:8761/eureka
      - DB_HOST=192.168.15.14
      - DB_PORT=3306
      - DB_USER=rcosta
      - DB_PASSWORD=rafa1234
    networks:
      - hml_network
    entrypoint: ["sh", "-c", "./wait-for-it.sh gateway_hml:8765 -- ./start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-account-2:
    build:
      context: ./microservices/api-account
    container_name: api_account_2_hml
    ports:
      - "8082:8080"
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=hml
      - SPRING_APPLICATION_INSTANCE_ID=account-2
      - EUREKA_SERVER_URL=http://server:8761/eureka
      - DB_HOST=192.168.15.14
      - DB_PORT=3306
      - DB_USER=rcosta
      - DB_PASSWORD=rafa1234
    networks:
      - hml_network
    entrypoint: ["sh", "-c", "./wait-for-it.sh gateway_hml:8765 -- ./start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-credit-1:
    build:
      context: ./microservices/api-credit
    container_name: api_credit_1_hml
    ports:
      - "8083:8080"
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=hml
      - SPRING_APPLICATION_INSTANCE_ID=credit-1
      - EUREKA_SERVER_URL=http://server:8761/eureka
      - DB_HOST=192.168.15.14
      - DB_PORT=3306
      - DB_USER=rcosta
      - DB_PASSWORD=rafa1234
    networks:
      - hml_network
    entrypoint: ["sh", "-c", "./wait-for-it.sh gateway_hml:8765 -- ./start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-credit-2:
    build:
      context: ./microservices/api-credit
    container_name: api_credit_2_hml
    ports:
      - "8084:8080"
    depends_on:
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=hml
      - SPRING_APPLICATION_INSTANCE_ID=credit-2
      - EUREKA_SERVER_URL=http://server:8761/eureka
      - DB_HOST=192.168.15.14
      - DB_PORT=3306
      - DB_USER=rcosta
      - DB_PASSWORD=rafa1234
    networks:
      - hml_network
    entrypoint: ["sh", "-c", "./wait-for-it.sh gateway_hml:8765 -- ./start.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  hml_network:
    driver: bridge
